### ISSUE TITLE
Latest Version breaks functionality

### ISSUE THREAD

**Issue by f8al** [mboot-github/WhoisDomain#13]
## Describe the bug
as of one of the more recent updates, the whois object no longer works and instead returns a timeout error whenever

## To Reproduce
use the example code provided in the readme

```
import whoisdomain as whois
d=whois.query('google.com')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/whoisdomain/whoisCliInterface.py", line 135, in runWhoisCliOnThisOs
    self.rawWhoisResultString = self.processHandle.communicate(timeout=self.pc.timeout,)[
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 1209, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 2101, in _communicate
    self._check_timeout(endtime, orig_timeout,
  File "/usr/lib/python3.11/subprocess.py", line 1253, in _check_timeout
    raise TimeoutExpired(
subprocess.TimeoutExpired: Command '['stdbuf', '-o0', 'whois', 'google.com']' timed out after 0.0 seconds

```
## Expected behavior
```
python
>>> import whoisdomain as whois
>>> d = whois.query('google.com')
>>> print(d.__dict__)
{'name': 'google.com', 'tld': 'com', 'registrar': 'MarkMonitor, Inc.', 'registrant_country': 'US', 'creation_date': datetime.datetime(1997, 9, 15, 9, 0), 'expiration_date': datetime.datetime(2028, 9, 13, 9, 0), 'last_updated': datetime.datetime(2019, 9, 9, 17, 39, 4), 'status': 'clientUpdateProhibited (https://www.icann.org/epp#clientUpdateProhibited)', 'statuses': ['clientDeleteProhibited (https://www.icann.org/epp#clientDeleteProhibited)', 'clientTransferProhibited (https://www.icann.org/epp#clientTransferProhibited)', 'clientUpdateProhibited (https://www.icann.org/epp#clientUpdateProhibited)', 'serverDeleteProhibited (https://www.icann.org/epp#serverDeleteProhibited)', 'serverTransferProhibited (https://www.icann.org/epp#serverTransferProhibited)', 'serverUpdateProhibited (https://www.icann.org/epp#serverUpdateProhibited)'], 'dnssec': False, 'name_servers': ['ns1.google.com', 'ns2.google.com', 'ns3.google.com', 'ns4.google.com'], 'registrant': 'Google LLC', 'emails': ['abusecomplaints@markmonitor.com', 'whoisrequest@markmonitor.com']}

```
## Screenshots
Kali linux:
<img width="936" alt="image" src="https://github.com/mboot-github/WhoisDomain/assets/7221183/621deb02-ee0c-4a8f-8569-4b2a8591d448">
macOS
<img width="1065" alt="image" src="https://github.com/mboot-github/WhoisDomain/assets/7221183/b5a2fd75-7dc0-4b75-8441-d2c4bd24e34d">

## Desktop (please complete the following information):
tested on both latest MacOS 13.4.1c as well as Kali Linux 2023.2a with same results

**Comment by f8al** [comment]
this break was introduced in version 1.20230804.2 on August 4th
pinning to the earlier versions makes it work
`pip install whoisdomain==1.20230720.2`

**Comment by mboot-github** [comment]
yes also in the latest version, will hava alook today

**Comment by mboot-github** [comment]
without further comment we will close the issue next week.
